// Code generated by protoc-gen-go. DO NOT EDIT.
// source: data.proto

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	data.proto

It has these top-level messages:
	RequestPing
	RequestContact
	RequestData
	RequestStore
	ReplyPing
	ReplyContactList
	ReplyData
	ReplyStore
	WrapperMessage
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RequestPing struct {
}

func (m *RequestPing) Reset()                    { *m = RequestPing{} }
func (m *RequestPing) String() string            { return proto.CompactTextString(m) }
func (*RequestPing) ProtoMessage()               {}
func (*RequestPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RequestContact struct {
	Target string `protobuf:"bytes,1,opt,name=Target" json:"Target,omitempty"`
}

func (m *RequestContact) Reset()                    { *m = RequestContact{} }
func (m *RequestContact) String() string            { return proto.CompactTextString(m) }
func (*RequestContact) ProtoMessage()               {}
func (*RequestContact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RequestContact) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type RequestData struct {
	Key string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
}

func (m *RequestData) Reset()                    { *m = RequestData{} }
func (m *RequestData) String() string            { return proto.CompactTextString(m) }
func (*RequestData) ProtoMessage()               {}
func (*RequestData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *RequestData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RequestStore struct {
	Key  string `protobuf:"bytes,1,opt,name=Key" json:"Key,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
}

func (m *RequestStore) Reset()                    { *m = RequestStore{} }
func (m *RequestStore) String() string            { return proto.CompactTextString(m) }
func (*RequestStore) ProtoMessage()               {}
func (*RequestStore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *RequestStore) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *RequestStore) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ReplyPing struct {
}

func (m *ReplyPing) Reset()                    { *m = ReplyPing{} }
func (m *ReplyPing) String() string            { return proto.CompactTextString(m) }
func (*ReplyPing) ProtoMessage()               {}
func (*ReplyPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReplyPing_Contact struct {
	ID      string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address" json:"Address,omitempty"`
}

func (m *ReplyPing_Contact) Reset()                    { *m = ReplyPing_Contact{} }
func (m *ReplyPing_Contact) String() string            { return proto.CompactTextString(m) }
func (*ReplyPing_Contact) ProtoMessage()               {}
func (*ReplyPing_Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4, 0} }

func (m *ReplyPing_Contact) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReplyPing_Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReplyContactList struct {
	Contacts []*ReplyContactList_Contact `protobuf:"bytes,1,rep,name=Contacts" json:"Contacts,omitempty"`
}

func (m *ReplyContactList) Reset()                    { *m = ReplyContactList{} }
func (m *ReplyContactList) String() string            { return proto.CompactTextString(m) }
func (*ReplyContactList) ProtoMessage()               {}
func (*ReplyContactList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReplyContactList) GetContacts() []*ReplyContactList_Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type ReplyContactList_Contact struct {
	ID      string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Address string `protobuf:"bytes,2,opt,name=Address" json:"Address,omitempty"`
}

func (m *ReplyContactList_Contact) Reset()                    { *m = ReplyContactList_Contact{} }
func (m *ReplyContactList_Contact) String() string            { return proto.CompactTextString(m) }
func (*ReplyContactList_Contact) ProtoMessage()               {}
func (*ReplyContactList_Contact) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *ReplyContactList_Contact) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReplyContactList_Contact) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ReplyData struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *ReplyData) Reset()                    { *m = ReplyData{} }
func (m *ReplyData) String() string            { return proto.CompactTextString(m) }
func (*ReplyData) ProtoMessage()               {}
func (*ReplyData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ReplyData) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type ReplyStore struct {
	Data string `protobuf:"bytes,1,opt,name=Data" json:"Data,omitempty"`
}

func (m *ReplyStore) Reset()                    { *m = ReplyStore{} }
func (m *ReplyStore) String() string            { return proto.CompactTextString(m) }
func (*ReplyStore) ProtoMessage()               {}
func (*ReplyStore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ReplyStore) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type WrapperMessage struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	SourceID  string `protobuf:"bytes,2,opt,name=SourceID" json:"SourceID,omitempty"`
	RequestID string `protobuf:"bytes,3,opt,name=RequestID" json:"RequestID,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*WrapperMessage_RequestPing
	//	*WrapperMessage_RequestContact
	//	*WrapperMessage_RequestData
	//	*WrapperMessage_RequestStore
	//	*WrapperMessage_ReplyPing
	//	*WrapperMessage_ReplyContactList
	//	*WrapperMessage_ReplyData
	//	*WrapperMessage_ReplyStore
	Msg isWrapperMessage_Msg `protobuf_oneof:"msg"`
}

func (m *WrapperMessage) Reset()                    { *m = WrapperMessage{} }
func (m *WrapperMessage) String() string            { return proto.CompactTextString(m) }
func (*WrapperMessage) ProtoMessage()               {}
func (*WrapperMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type isWrapperMessage_Msg interface {
	isWrapperMessage_Msg()
}

type WrapperMessage_RequestPing struct {
	RequestPing *RequestPing `protobuf:"bytes,4,opt,name=requestPing,oneof"`
}
type WrapperMessage_RequestContact struct {
	RequestContact *RequestContact `protobuf:"bytes,5,opt,name=requestContact,oneof"`
}
type WrapperMessage_RequestData struct {
	RequestData *RequestData `protobuf:"bytes,6,opt,name=requestData,oneof"`
}
type WrapperMessage_RequestStore struct {
	RequestStore *RequestStore `protobuf:"bytes,7,opt,name=requestStore,oneof"`
}
type WrapperMessage_ReplyPing struct {
	ReplyPing *ReplyPing `protobuf:"bytes,8,opt,name=replyPing,oneof"`
}
type WrapperMessage_ReplyContactList struct {
	ReplyContactList *ReplyContactList `protobuf:"bytes,9,opt,name=replyContactList,oneof"`
}
type WrapperMessage_ReplyData struct {
	ReplyData *ReplyData `protobuf:"bytes,10,opt,name=replyData,oneof"`
}
type WrapperMessage_ReplyStore struct {
	ReplyStore *ReplyStore `protobuf:"bytes,11,opt,name=replyStore,oneof"`
}

func (*WrapperMessage_RequestPing) isWrapperMessage_Msg()      {}
func (*WrapperMessage_RequestContact) isWrapperMessage_Msg()   {}
func (*WrapperMessage_RequestData) isWrapperMessage_Msg()      {}
func (*WrapperMessage_RequestStore) isWrapperMessage_Msg()     {}
func (*WrapperMessage_ReplyPing) isWrapperMessage_Msg()        {}
func (*WrapperMessage_ReplyContactList) isWrapperMessage_Msg() {}
func (*WrapperMessage_ReplyData) isWrapperMessage_Msg()        {}
func (*WrapperMessage_ReplyStore) isWrapperMessage_Msg()       {}

func (m *WrapperMessage) GetMsg() isWrapperMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *WrapperMessage) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *WrapperMessage) GetSourceID() string {
	if m != nil {
		return m.SourceID
	}
	return ""
}

func (m *WrapperMessage) GetRequestID() string {
	if m != nil {
		return m.RequestID
	}
	return ""
}

func (m *WrapperMessage) GetRequestPing() *RequestPing {
	if x, ok := m.GetMsg().(*WrapperMessage_RequestPing); ok {
		return x.RequestPing
	}
	return nil
}

func (m *WrapperMessage) GetRequestContact() *RequestContact {
	if x, ok := m.GetMsg().(*WrapperMessage_RequestContact); ok {
		return x.RequestContact
	}
	return nil
}

func (m *WrapperMessage) GetRequestData() *RequestData {
	if x, ok := m.GetMsg().(*WrapperMessage_RequestData); ok {
		return x.RequestData
	}
	return nil
}

func (m *WrapperMessage) GetRequestStore() *RequestStore {
	if x, ok := m.GetMsg().(*WrapperMessage_RequestStore); ok {
		return x.RequestStore
	}
	return nil
}

func (m *WrapperMessage) GetReplyPing() *ReplyPing {
	if x, ok := m.GetMsg().(*WrapperMessage_ReplyPing); ok {
		return x.ReplyPing
	}
	return nil
}

func (m *WrapperMessage) GetReplyContactList() *ReplyContactList {
	if x, ok := m.GetMsg().(*WrapperMessage_ReplyContactList); ok {
		return x.ReplyContactList
	}
	return nil
}

func (m *WrapperMessage) GetReplyData() *ReplyData {
	if x, ok := m.GetMsg().(*WrapperMessage_ReplyData); ok {
		return x.ReplyData
	}
	return nil
}

func (m *WrapperMessage) GetReplyStore() *ReplyStore {
	if x, ok := m.GetMsg().(*WrapperMessage_ReplyStore); ok {
		return x.ReplyStore
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*WrapperMessage) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _WrapperMessage_OneofMarshaler, _WrapperMessage_OneofUnmarshaler, _WrapperMessage_OneofSizer, []interface{}{
		(*WrapperMessage_RequestPing)(nil),
		(*WrapperMessage_RequestContact)(nil),
		(*WrapperMessage_RequestData)(nil),
		(*WrapperMessage_RequestStore)(nil),
		(*WrapperMessage_ReplyPing)(nil),
		(*WrapperMessage_ReplyContactList)(nil),
		(*WrapperMessage_ReplyData)(nil),
		(*WrapperMessage_ReplyStore)(nil),
	}
}

func _WrapperMessage_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*WrapperMessage)
	// msg
	switch x := m.Msg.(type) {
	case *WrapperMessage_RequestPing:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequestPing); err != nil {
			return err
		}
	case *WrapperMessage_RequestContact:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequestContact); err != nil {
			return err
		}
	case *WrapperMessage_RequestData:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequestData); err != nil {
			return err
		}
	case *WrapperMessage_RequestStore:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.RequestStore); err != nil {
			return err
		}
	case *WrapperMessage_ReplyPing:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplyPing); err != nil {
			return err
		}
	case *WrapperMessage_ReplyContactList:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplyContactList); err != nil {
			return err
		}
	case *WrapperMessage_ReplyData:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplyData); err != nil {
			return err
		}
	case *WrapperMessage_ReplyStore:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ReplyStore); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("WrapperMessage.Msg has unexpected type %T", x)
	}
	return nil
}

func _WrapperMessage_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*WrapperMessage)
	switch tag {
	case 4: // msg.requestPing
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestPing)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_RequestPing{msg}
		return true, err
	case 5: // msg.requestContact
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestContact)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_RequestContact{msg}
		return true, err
	case 6: // msg.requestData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestData)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_RequestData{msg}
		return true, err
	case 7: // msg.requestStore
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(RequestStore)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_RequestStore{msg}
		return true, err
	case 8: // msg.replyPing
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplyPing)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_ReplyPing{msg}
		return true, err
	case 9: // msg.replyContactList
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplyContactList)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_ReplyContactList{msg}
		return true, err
	case 10: // msg.replyData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplyData)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_ReplyData{msg}
		return true, err
	case 11: // msg.replyStore
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReplyStore)
		err := b.DecodeMessage(msg)
		m.Msg = &WrapperMessage_ReplyStore{msg}
		return true, err
	default:
		return false, nil
	}
}

func _WrapperMessage_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*WrapperMessage)
	// msg
	switch x := m.Msg.(type) {
	case *WrapperMessage_RequestPing:
		s := proto.Size(x.RequestPing)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_RequestContact:
		s := proto.Size(x.RequestContact)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_RequestData:
		s := proto.Size(x.RequestData)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_RequestStore:
		s := proto.Size(x.RequestStore)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_ReplyPing:
		s := proto.Size(x.ReplyPing)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_ReplyContactList:
		s := proto.Size(x.ReplyContactList)
		n += proto.SizeVarint(9<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_ReplyData:
		s := proto.Size(x.ReplyData)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *WrapperMessage_ReplyStore:
		s := proto.Size(x.ReplyStore)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*RequestPing)(nil), "main.RequestPing")
	proto.RegisterType((*RequestContact)(nil), "main.RequestContact")
	proto.RegisterType((*RequestData)(nil), "main.RequestData")
	proto.RegisterType((*RequestStore)(nil), "main.RequestStore")
	proto.RegisterType((*ReplyPing)(nil), "main.ReplyPing")
	proto.RegisterType((*ReplyPing_Contact)(nil), "main.ReplyPing.Contact")
	proto.RegisterType((*ReplyContactList)(nil), "main.ReplyContactList")
	proto.RegisterType((*ReplyContactList_Contact)(nil), "main.ReplyContactList.Contact")
	proto.RegisterType((*ReplyData)(nil), "main.ReplyData")
	proto.RegisterType((*ReplyStore)(nil), "main.ReplyStore")
	proto.RegisterType((*WrapperMessage)(nil), "main.WrapperMessage")
}

func init() { proto.RegisterFile("data.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x8e, 0x94, 0x40,
	0x10, 0xc6, 0x61, 0x60, 0x67, 0x86, 0x62, 0x45, 0xec, 0x98, 0x4d, 0x67, 0x63, 0x5c, 0xc2, 0x89,
	0x13, 0x26, 0xb3, 0x9a, 0x18, 0x0f, 0xc6, 0x3f, 0x1c, 0x20, 0x6a, 0x62, 0x7a, 0x4d, 0x3c, 0xb7,
	0x3b, 0x1d, 0x32, 0x89, 0x3b, 0x60, 0x77, 0xcf, 0x61, 0xce, 0x3e, 0x8b, 0xef, 0x69, 0x28, 0x1b,
	0x68, 0x86, 0x39, 0x79, 0xeb, 0xea, 0xfa, 0x7e, 0x54, 0x7d, 0xd5, 0x05, 0xc0, 0x96, 0x6b, 0x9e,
	0xb7, 0xb2, 0xd1, 0x0d, 0xf1, 0x1f, 0xf8, 0x6e, 0x9f, 0x3e, 0x82, 0x90, 0x89, 0x5f, 0x07, 0xa1,
	0xf4, 0xd7, 0xdd, 0xbe, 0x4e, 0x33, 0x88, 0x4c, 0xf8, 0xb1, 0xd9, 0x6b, 0x7e, 0xaf, 0xc9, 0x15,
	0x2c, 0xbf, 0x71, 0x59, 0x0b, 0x4d, 0xdd, 0xc4, 0xcd, 0x02, 0x66, 0xa2, 0xf4, 0x66, 0x00, 0x0b,
	0xae, 0x39, 0x89, 0xc1, 0xfb, 0x24, 0x8e, 0x46, 0xd3, 0x1d, 0xd3, 0x97, 0x70, 0x69, 0x04, 0x77,
	0xba, 0x91, 0x62, 0xae, 0x20, 0x04, 0xfc, 0x8e, 0xa5, 0x0b, 0xbc, 0xc2, 0x73, 0xfa, 0x0e, 0x02,
	0x26, 0xda, 0x9f, 0xc7, 0xae, 0x9b, 0xeb, 0x5b, 0x58, 0xf5, 0x6d, 0x44, 0xb0, 0xa8, 0x0a, 0x03,
	0x2f, 0xaa, 0x82, 0x50, 0x58, 0xbd, 0xdf, 0x6e, 0xa5, 0x50, 0xca, 0xe0, 0x7d, 0x98, 0xfe, 0x76,
	0x21, 0xc6, 0x4f, 0x18, 0xf4, 0xf3, 0x4e, 0x69, 0xf2, 0x06, 0xd6, 0x26, 0x54, 0xd4, 0x4d, 0xbc,
	0x2c, 0xdc, 0x3c, 0xcf, 0x3b, 0xff, 0xf9, 0xa9, 0x32, 0x37, 0x67, 0x36, 0xe8, 0xff, 0xaf, 0x8b,
	0x1b, 0xe3, 0x03, 0x87, 0xd3, 0x1b, 0x75, 0x2d, 0xa3, 0x09, 0x00, 0x0a, 0xfe, 0x0d, 0xe7, 0x9c,
	0xe2, 0x8f, 0x0f, 0xd1, 0x77, 0xc9, 0xdb, 0x56, 0xc8, 0x2f, 0x42, 0x29, 0x5e, 0x8b, 0x59, 0xfd,
	0x6b, 0x58, 0xdf, 0x35, 0x07, 0x79, 0x2f, 0xaa, 0xc2, 0x34, 0x30, 0xc4, 0xe4, 0x59, 0xd7, 0x01,
	0xce, 0xbf, 0x2a, 0xa8, 0x87, 0xc9, 0xf1, 0x82, 0xbc, 0x82, 0x50, 0x8e, 0xef, 0x4e, 0xfd, 0xc4,
	0xcd, 0xc2, 0xcd, 0x93, 0x7e, 0x26, 0x43, 0xa2, 0x74, 0x98, 0xad, 0x23, 0x6f, 0x21, 0x92, 0x93,
	0xfd, 0xa0, 0x17, 0x48, 0x3e, 0x9d, 0x90, 0x26, 0x57, 0x3a, 0xec, 0x44, 0x6d, 0x95, 0x45, 0xbb,
	0xcb, 0x33, 0x65, 0xbb, 0x84, 0x55, 0x16, 0x07, 0xf8, 0x1a, 0x2e, 0xa5, 0xb5, 0x4b, 0x74, 0x85,
	0x1c, 0x99, 0x70, 0x98, 0x29, 0x1d, 0x36, 0x51, 0x92, 0x17, 0x10, 0xc8, 0x7e, 0x9f, 0xe8, 0x1a,
	0xb1, 0xc7, 0xd6, 0xcb, 0x1b, 0x8f, 0xa3, 0x86, 0x14, 0x10, 0xcb, 0x93, 0x9d, 0xa0, 0x01, 0x72,
	0x57, 0xe7, 0x37, 0xa6, 0x74, 0xd8, 0x8c, 0x18, 0xca, 0xa2, 0x4b, 0x98, 0x95, 0x35, 0x1e, 0x47,
	0x0d, 0xd9, 0x00, 0xc8, 0x61, 0x1d, 0x68, 0x88, 0x44, 0x6c, 0x11, 0xbd, 0x3b, 0x4b, 0xf5, 0xe1,
	0x02, 0xbc, 0x07, 0x55, 0xff, 0x58, 0xe2, 0xff, 0x7c, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0xeb,
	0xe5, 0xd5, 0x49, 0xdd, 0x03, 0x00, 0x00,
}
